version: '3'

services:
    nfs-server:
      build: ./
      container_name: nfs
      ports:
         - "2049:2049"
         - "111:111"
         - "32765:32765"
         - "32767:32767"
         - "2049:2049/udp"
         - "111:111/udp"
         - "32765:32765/udp"
         - "32767:32767/udp"
      volumes:
         - ../nfs:/nfs
         - ./conf//exports.txt:/etc/exports
      privileged: true
